baseURL = "https://hatateaya.github.io/"
languageCode = "zh-cn"
title = "HatateAya's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Hatate Aya"
  description = "Ayayayayayayaya..."
  github = "hatateaya"
  twitter = "amcje1"
  email = "amcjedhfeh@gmail.com"
  url = "https://hatateaya.github.io"
  keywords = "blog"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "China"
  userStatusEmoji = "😀"
  enableGitalk = false
    
#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/hatateaya"
#  [[params.links]]
#    title = "Link2"
#    href = "https://meik2333.com"
#    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
